name: TEMPLATE_LANGUAGE
on:
  schedule:
    - cron: 'TEMPLATE_MIN TEMPLATE_HOUR * * *'

jobs:
  make-docs:
    runs-on: ubuntu-latest
    env:
      LANGUAGE: "TEMPLATE_LANGUAGE"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: install wandbox-api
      run: pip install wandbox-api
    - name: wandbox-api version
      run: wandbox -v
    - name: clean
      run: |
        rm -rf "./docs/shields/${LANGUAGE}"
    - name: make docs
      run: |
        ./docs/health-check.sh -l "${LANGUAGE}"
        ./docs/health-check-all-report.sh -l "${LANGUAGE}"
    - name: git config
      run: |
        git config --local user.name github-actions[bot]
        git config --local user.email github-actions[bot]@users.noreply.github.com
    - name: commit
      run: |
        git add .
        git commit -m "update ${LANGUAGE}" || true
        git rebase origin/main
    - name: push
      run: |
        git push origin main
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     base: main
    #     branch: feature/cpp
    #     title: "update c++"
    #     commit-message: "update c++"
    #     delete-branch: true
    #     labels: "status"
