name: Update cron workflows
on:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  update-cron-workflows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: install wandbox-api
      run: pip install wandbox-api
    - name: wandbox-api version
      run: wandbox -v
    - name: make workflows
      run: |
        ./.github/workflows-template/make.sh
    - name: git config
      run: |
        git config --local user.name ${{ github.actor }}
        git config --local user.email ${{ github.actor }}@users.noreply.github.com
    - name: commit
      run: |
        git add .
        git commit -m "update cron workflows" || true
    - name: push
      if: github.event_name == 'cron'
      run: |
        git push origin main
